apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: brewingelixir/myapp:0.0.2
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE 
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: key_base
